agents:
  queue: "selfhosted"

steps:
  - label: ":package: Build binary"
    key: "build"
    plugins:
      - docker#v5.13.0:
          image: "golang:1.18.0"
    command:
      - pwd
      - ls -R
      - go build -o ./dist/my-app ./hello
    artifact_paths:
      - "./dist/my-app"

  - block: "who is this"
    key: "block"
    fields:
      - text: "Name"
        key: "some_name"

  - label: ":rocket: Run binary"
    key: "run-binary"
    depends_on: "block"
    command:
      - NAME=$(buildkite-agent meta-data get some_name)
      - echo ${NAME}
      - buildkite-agent artifact download "dist/my-app" .
      - chmod +x dist/my-app
      - ./dist/my-app $(buildkite-agent meta-data get some_name)
